---
title: Activity Diagram - سامانه ثبت غذا
---

stateDiagram-v2
    [*] --> ورود_کاربر
    ورود_کاربر --> بررسی_ثبت_نام : بررسی اطلاعات کاربر
    بررسی_ثبت_نام --> ثبت_نام : کاربر جدید
    ثبت_نام --> ورود_کاربر_پس_از_ثبت_نام
    ورود_کاربر_پس_از_ثبت_نام --> نمایش_منو

    بررسی_ثبت_نام --> نمایش_منو : کاربر قبلاً ثبت‌نام کرده

    state نمایش_منو {
        [*] --> مشاهده_منوی_غذا
        مشاهده_منوی_غذا --> انتخاب_غذا
        انتخاب_غذا --> ثبت_سفارش
        ثبت_سفارش --> تأیید_سفارش : تأیید نهایی کاربر
        تأیید_سفارش --> بررسی_مدیر : ارسال به مدیر
    }

    بررسی_مدیر --> تأیید_مدیر : تایید سفارش
    بررسی_مدیر --> رد_سفارش : رد سفارش
    تأیید_مدیر --> آماده_سازی_غذا
    آماده_سازی_غذا --> اعلام_به_کاربر
    اعلام_به_کاربر --> [*]
    رد_سفارش --> اطلاع_لغو
    اطلاع_لغو --> [*]
